package view;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;

public class LoginView extends javax.swing.JFrame {

    
    public LoginView() {
        initComponents();
    }
    
    public String getUsername (){
        return jTextFieldUsername.getText() ;
    }
    public String getPassword (){
        return jPasswordFieldPassword.getText() ;
    }
    
    public void loginListener(ActionListener loginListenerButton){
        jButtonLogin.addActionListener(loginListenerButton);
    }
    public void signUpMouseMoved( MouseListener signUpMouseListener) {                                        
        jLabelSignUp.addMouseListener(signUpMouseListener);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        Top = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        WelcomeBack = new javax.swing.JLabel();
        TextFields = new javax.swing.JPanel();
        JPUsername = new javax.swing.JPanel();
        jTextFieldUsername = new javax.swing.JTextField();
        jLabelUsername = new javax.swing.JLabel();
        jppassword = new javax.swing.JPanel();
        jLabelPasswoed = new javax.swing.JLabel();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jPanel7 = new javax.swing.JPanel();
        RememberMe = new javax.swing.JCheckBox();
        ForgotUrPassword = new javax.swing.JLabel();
        Button = new javax.swing.JPanel();
        jButtonLogin = new javax.swing.JButton();
        SignUp = new javax.swing.JPanel();
        jLabelSignUp = new javax.swing.JLabel();
        Image = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QuizApp || Login");
        setResizable(false);

        body.setPreferredSize(new java.awt.Dimension(400, 0));

        Top.setPreferredSize(new java.awt.Dimension(400, 100));

        Logo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Logo.png"))); // NOI18N

        WelcomeBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        WelcomeBack.setText("Welcome Back");

        javax.swing.GroupLayout TopLayout = new javax.swing.GroupLayout(Top);
        Top.setLayout(TopLayout);
        TopLayout.setHorizontalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopLayout.createSequentialGroup()
                .addGroup(TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TopLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(WelcomeBack))
                    .addGroup(TopLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(Logo)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        TopLayout.setVerticalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(WelcomeBack)
                .addContainerGap())
        );

        body.add(Top);

        TextFields.setPreferredSize(new java.awt.Dimension(400, 150));

        JPUsername.setPreferredSize(new java.awt.Dimension(250, 50));
        JPUsername.setLayout(new java.awt.BorderLayout(4, 4));
        JPUsername.add(jTextFieldUsername, java.awt.BorderLayout.PAGE_END);

        jLabelUsername.setText("Username");
        JPUsername.add(jLabelUsername, java.awt.BorderLayout.LINE_START);

        TextFields.add(JPUsername);

        jppassword.setPreferredSize(new java.awt.Dimension(250, 50));
        jppassword.setLayout(new java.awt.BorderLayout(4, 4));

        jLabelPasswoed.setText("Password");
        jppassword.add(jLabelPasswoed, java.awt.BorderLayout.LINE_START);
        jppassword.add(jPasswordFieldPassword, java.awt.BorderLayout.PAGE_END);

        TextFields.add(jppassword);

        jPanel7.setPreferredSize(new java.awt.Dimension(250, 25));
        jPanel7.setLayout(new java.awt.BorderLayout());

        RememberMe.setSelected(true);
        RememberMe.setText("Remember me");
        jPanel7.add(RememberMe, java.awt.BorderLayout.WEST);

        ForgotUrPassword.setForeground(new java.awt.Color(255, 153, 153));
        ForgotUrPassword.setText("Forgot your password?");
        jPanel7.add(ForgotUrPassword, java.awt.BorderLayout.EAST);

        TextFields.add(jPanel7);

        body.add(TextFields);

        Button.setPreferredSize(new java.awt.Dimension(400, 40));

        jButtonLogin.setBackground(new java.awt.Color(84, 86, 255));
        jButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8_login_16px_2.png"))); // NOI18N
        jButtonLogin.setText("Login");
        jButtonLogin.setPreferredSize(new java.awt.Dimension(250, 30));
        Button.add(jButtonLogin);

        body.add(Button);

        SignUp.setPreferredSize(new java.awt.Dimension(400, 40));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
        flowLayout1.setAlignOnBaseline(true);
        SignUp.setLayout(flowLayout1);

        jLabelSignUp.setText("Don't hava an account yet? Sign up");
        SignUp.add(jLabelSignUp);

        body.add(SignUp);

        getContentPane().add(body, java.awt.BorderLayout.WEST);

        Image.setBackground(new java.awt.Color(0, 32, 74));
        Image.setPreferredSize(new java.awt.Dimension(400, 420));
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20);
        flowLayout2.setAlignOnBaseline(true);
        Image.setLayout(flowLayout2);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Computer login.png"))); // NOI18N
        Image.add(jLabel7);

        getContentPane().add(Image, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Button;
    private javax.swing.JLabel ForgotUrPassword;
    private javax.swing.JPanel Image;
    private javax.swing.JPanel JPUsername;
    private javax.swing.JLabel Logo;
    private javax.swing.JCheckBox RememberMe;
    private javax.swing.JPanel SignUp;
    private javax.swing.JPanel TextFields;
    private javax.swing.JPanel Top;
    private javax.swing.JLabel WelcomeBack;
    private javax.swing.JPanel body;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelPasswoed;
    private javax.swing.JLabel jLabelSignUp;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JTextField jTextFieldUsername;
    private javax.swing.JPanel jppassword;
    // End of variables declaration//GEN-END:variables
}
