package view;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import static model.UsersModel.errmsgBox;


public class QuizView extends javax.swing.JFrame {

     
    public QuizView( ) {
        initComponents();
    }
    
    public void setNameOfQuiz (String name){
        NameOfQuiz.setText(name);
    }
    public void setTextOfQuestion (String question){
        TextOfQuestion.setText(question);
    }
    public void setTextOfChoiceOne (String choice){
        ChoiceOne.setText(choice);
    }
    public void setTextOfChoiceTwo (String choice){
        ChoiceTwo.setText(choice);
    }
    public void setTextOfChoiceThree (String choice){
        ChoiceThree.setText(choice);
    }
    public void setTextOfChoiceFour (String choice){
        ChoiceFour.setText(choice);
    }
    public void setNumOfQuestion (String strNumOfQuestion){
        numOfQuestion.setText(strNumOfQuestion);
    }
   public void nextQuestion (ActionListener nextQuestionListenerButton) {                                       
        jButtonNext.addActionListener(nextQuestionListenerButton);
    }
    public int getNumSelectionButton (){
        try{
        if(Choices.getSelection().equals(jCheckBoxOne.getModel())){
            return 1;
        }else if(Choices.getSelection().equals(jCheckBoxTwo.getModel())){
            return 2;
        }else if(Choices.getSelection().equals(jCheckBoxThree.getModel())){
            return 3;
        }else if(Choices.getSelection().equals(jCheckBoxFour.getModel())){
            return 4;
        }}catch(NullPointerException ex){
            errmsgBox("Choose any choice");
        }
        return 0;
    }
    public void closeButton (ActionListener closeListenerButton) {                                       
        jButtonClose.addActionListener(closeListenerButton);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Choices = new javax.swing.ButtonGroup();
        jPanelImg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NameOfQuiz = new javax.swing.JLabel();
        jButtonClose = new javax.swing.JButton();
        jPanelQuestions = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        numOfQuestion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextOfQuestion = new javax.swing.JLabel();
        ChoiceOne = new javax.swing.JLabel();
        jCheckBoxOne = new javax.swing.JCheckBox();
        ChoiceTwo = new javax.swing.JLabel();
        jCheckBoxTwo = new javax.swing.JCheckBox();
        ChoiceThree = new javax.swing.JLabel();
        jCheckBoxThree = new javax.swing.JCheckBox();
        ChoiceFour = new javax.swing.JLabel();
        jCheckBoxFour = new javax.swing.JCheckBox();
        jButtonNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/OnlineQuiz.png"))); // NOI18N

        NameOfQuiz.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        NameOfQuiz.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameOfQuiz.setText("NameOfQuiz");

        jButtonClose.setText("Close");

        javax.swing.GroupLayout jPanelImgLayout = new javax.swing.GroupLayout(jPanelImg);
        jPanelImg.setLayout(jPanelImgLayout);
        jPanelImgLayout.setHorizontalGroup(
            jPanelImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameOfQuiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelImgLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelImgLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jButtonClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelImgLayout.setVerticalGroup(
            jPanelImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImgLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButtonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(NameOfQuiz)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 650));

        numOfQuestion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numOfQuestion.setForeground(new java.awt.Color(255, 255, 255));
        numOfQuestion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numOfQuestion.setText("numOfQuestion");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Question: ");

        TextOfQuestion.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        TextOfQuestion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextOfQuestion.setText("Text Of Question");

        ChoiceOne.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ChoiceOne.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChoiceOne.setText("Text Of Choices");

        Choices.add(jCheckBoxOne);

        ChoiceTwo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ChoiceTwo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChoiceTwo.setText("Text Of Choices");

        Choices.add(jCheckBoxTwo);
        jCheckBoxTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTwoActionPerformed(evt);
            }
        });

        ChoiceThree.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ChoiceThree.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChoiceThree.setText("Text Of Choices");

        Choices.add(jCheckBoxThree);

        ChoiceFour.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ChoiceFour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChoiceFour.setText("Text Of Choices");

        Choices.add(jCheckBoxFour);

        jButtonNext.setText("NEXT");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 489, Short.MAX_VALUE)
                .addComponent(jButtonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(374, 374, 374))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBoxTwo)
                    .addComponent(jCheckBoxOne)
                    .addComponent(jCheckBoxThree)
                    .addComponent(jCheckBoxFour))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextOfQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numOfQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ChoiceThree, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChoiceTwo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChoiceOne, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChoiceFour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numOfQuestion)
                .addGap(33, 33, 33)
                .addComponent(TextOfQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBoxOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChoiceOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBoxTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChoiceTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBoxThree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChoiceThree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBoxFour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChoiceFour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButtonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(282, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelQuestionsLayout = new javax.swing.GroupLayout(jPanelQuestions);
        jPanelQuestions.setLayout(jPanelQuestionsLayout);
        jPanelQuestionsLayout.setHorizontalGroup(
            jPanelQuestionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuestionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1044, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelQuestionsLayout.setVerticalGroup(
            jPanelQuestionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelQuestions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelQuestions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTwoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTwoActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        Choices.clearSelection();
    }//GEN-LAST:event_jButtonNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ChoiceFour;
    private javax.swing.JLabel ChoiceOne;
    private javax.swing.JLabel ChoiceThree;
    private javax.swing.JLabel ChoiceTwo;
    private javax.swing.ButtonGroup Choices;
    private javax.swing.JLabel NameOfQuiz;
    private javax.swing.JLabel TextOfQuestion;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JCheckBox jCheckBoxFour;
    private javax.swing.JCheckBox jCheckBoxOne;
    private javax.swing.JCheckBox jCheckBoxThree;
    private javax.swing.JCheckBox jCheckBoxTwo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelImg;
    private javax.swing.JPanel jPanelQuestions;
    private javax.swing.JLabel numOfQuestion;
    // End of variables declaration//GEN-END:variables

    
}
