package view;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;


public class SignUpView extends javax.swing.JFrame {

    
    public SignUpView() {
        initComponents();
    }
    
    public String getFullName(){
        return jTextFieldFullName.getText();
    }
    public String getUsername(){
        return jTextFieldUsername.getText();
    }
    public String getEmail(){
        return jTextFieldEmail.getText();
    }
    public String getPhone(){
        return jTextFieldPhoneNumber.getText();
    }
    public String getPassword(){
        return jPasswordFieldPassword.getText();
    }
    public void signUpListener(ActionListener signUpListenerButton){
        jButtonSignUp.addActionListener(signUpListenerButton);
    }
    public void loginMouseMoved( MouseListener loginMouseListener) {                                        
        jLabelLogin.addMouseListener(loginMouseListener);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        Top = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        WelcomeBack = new javax.swing.JLabel();
        TextFields = new javax.swing.JPanel();
        JPFullName = new javax.swing.JPanel();
        jTextFieldFullName = new javax.swing.JTextField();
        jLabelFullName = new javax.swing.JLabel();
        JPUsername = new javax.swing.JPanel();
        jTextFieldUsername = new javax.swing.JTextField();
        jLabelUsername = new javax.swing.JLabel();
        JPEmail = new javax.swing.JPanel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        JPPhoneNumber = new javax.swing.JPanel();
        jTextFieldPhoneNumber = new javax.swing.JTextField();
        jLabelPhoneNumber = new javax.swing.JLabel();
        jppassword = new javax.swing.JPanel();
        jLabelPasswoed = new javax.swing.JLabel();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        Button = new javax.swing.JPanel();
        jButtonSignUp = new javax.swing.JButton();
        SignUp = new javax.swing.JPanel();
        jLabelLogin = new javax.swing.JLabel();
        Image = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(910, 550));
        setResizable(false);

        body.setPreferredSize(new java.awt.Dimension(400, 0));

        Top.setPreferredSize(new java.awt.Dimension(400, 100));

        Logo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Logo.png"))); // NOI18N

        WelcomeBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        WelcomeBack.setText("Create New Account");

        javax.swing.GroupLayout TopLayout = new javax.swing.GroupLayout(Top);
        Top.setLayout(TopLayout);
        TopLayout.setHorizontalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopLayout.createSequentialGroup()
                .addGroup(TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TopLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(Logo))
                    .addGroup(TopLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(WelcomeBack)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        TopLayout.setVerticalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WelcomeBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        body.add(Top);

        TextFields.setPreferredSize(new java.awt.Dimension(400, 290));

        JPFullName.setPreferredSize(new java.awt.Dimension(250, 50));
        JPFullName.setLayout(new java.awt.BorderLayout(4, 4));
        JPFullName.add(jTextFieldFullName, java.awt.BorderLayout.PAGE_END);

        jLabelFullName.setText("Full Name");
        JPFullName.add(jLabelFullName, java.awt.BorderLayout.LINE_START);

        TextFields.add(JPFullName);

        JPUsername.setPreferredSize(new java.awt.Dimension(250, 50));
        JPUsername.setLayout(new java.awt.BorderLayout(4, 4));
        JPUsername.add(jTextFieldUsername, java.awt.BorderLayout.PAGE_END);

        jLabelUsername.setText("Username");
        JPUsername.add(jLabelUsername, java.awt.BorderLayout.LINE_START);

        TextFields.add(JPUsername);

        JPEmail.setPreferredSize(new java.awt.Dimension(250, 50));
        JPEmail.setLayout(new java.awt.BorderLayout(4, 4));
        JPEmail.add(jTextFieldEmail, java.awt.BorderLayout.PAGE_END);

        jLabelEmail.setText("Email");
        JPEmail.add(jLabelEmail, java.awt.BorderLayout.LINE_START);

        TextFields.add(JPEmail);

        JPPhoneNumber.setPreferredSize(new java.awt.Dimension(250, 50));
        JPPhoneNumber.setLayout(new java.awt.BorderLayout(4, 4));

        jTextFieldPhoneNumber.setText("02");
        JPPhoneNumber.add(jTextFieldPhoneNumber, java.awt.BorderLayout.PAGE_END);

        jLabelPhoneNumber.setText("PhoneNumber");
        JPPhoneNumber.add(jLabelPhoneNumber, java.awt.BorderLayout.LINE_START);

        TextFields.add(JPPhoneNumber);

        jppassword.setPreferredSize(new java.awt.Dimension(250, 50));
        jppassword.setLayout(new java.awt.BorderLayout(4, 4));

        jLabelPasswoed.setText("Password");
        jppassword.add(jLabelPasswoed, java.awt.BorderLayout.LINE_START);
        jppassword.add(jPasswordFieldPassword, java.awt.BorderLayout.PAGE_END);

        TextFields.add(jppassword);

        body.add(TextFields);

        Button.setPreferredSize(new java.awt.Dimension(400, 40));

        jButtonSignUp.setBackground(new java.awt.Color(84, 86, 255));
        jButtonSignUp.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8_sign_up_in_calendar_16px.png"))); // NOI18N
        jButtonSignUp.setText("Sign Up");
        jButtonSignUp.setPreferredSize(new java.awt.Dimension(250, 30));
        Button.add(jButtonSignUp);

        body.add(Button);

        SignUp.setPreferredSize(new java.awt.Dimension(400, 40));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
        flowLayout1.setAlignOnBaseline(true);
        SignUp.setLayout(flowLayout1);

        jLabelLogin.setText("Already have an account? Log in");
        SignUp.add(jLabelLogin);

        body.add(SignUp);

        getContentPane().add(body, java.awt.BorderLayout.WEST);

        Image.setBackground(new java.awt.Color(0, 32, 74));
        Image.setPreferredSize(new java.awt.Dimension(400, 420));
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20);
        flowLayout2.setAlignOnBaseline(true);
        Image.setLayout(flowLayout2);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Computer sign up.png"))); // NOI18N
        Image.add(jLabel7);

        getContentPane().add(Image, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new SignUpView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Button;
    private javax.swing.JPanel Image;
    private javax.swing.JPanel JPEmail;
    private javax.swing.JPanel JPFullName;
    private javax.swing.JPanel JPPhoneNumber;
    private javax.swing.JPanel JPUsername;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel SignUp;
    private javax.swing.JPanel TextFields;
    private javax.swing.JPanel Top;
    private javax.swing.JLabel WelcomeBack;
    private javax.swing.JPanel body;
    private javax.swing.JButton jButtonSignUp;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFullName;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelPasswoed;
    private javax.swing.JLabel jLabelPhoneNumber;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFullName;
    private javax.swing.JTextField jTextFieldPhoneNumber;
    private javax.swing.JTextField jTextFieldUsername;
    private javax.swing.JPanel jppassword;
    // End of variables declaration//GEN-END:variables
}
